In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.colors as mcolors
plt.rcParams['font.sans-serif']=['SimHei']
plt.rcParams['axes.unicode_minus'] = False  # 用来正常显示负号

import cartopy.crs as ccrs
import cartopy.io.shapereader as shpreader
from cartopy.mpl.ticker import LongitudeFormatter,LatitudeFormatter
# import matplotlib.ticker as mticker

import numpy as np
import xarray as xr
import pandas as pd
import os
import arrow

In [4]:
ds = xr.open_dataset("H:/ecmwf/202301/era5-single-monthly-2013-2022.nc")
sst = ds['sst']
t2m = ds['t2m']
d2m = ds['d2m']
lon = ds['longitude']
lat = ds['latitude']

In [16]:
def month_selector(month):
    return (month == 1) | (month == 2)


In [18]:
ds_selected = ds.sel(longitude=110.25, latitude=20.0, time=month_selector(ds['time.month']))
# ds_selected = ds.sel(time=month_selector(ds['time.month']))
print(ds_selected)

<xarray.Dataset>
Dimensions:    (expver: 2, time: 20)
Coordinates:
    longitude  float32 110.2
    latitude   float32 20.0
  * expver     (expver) int32 1 5
  * time       (time) datetime64[ns] 2013-01-01 2013-02-01 ... 2022-02-01
Data variables:
    d2m        (time, expver) float32 ...
    t2m        (time, expver) float32 ...
    sst        (time, expver) float32 292.6 nan 293.4 nan ... nan 292.9 nan
Attributes:
    Conventions:  CF-1.6
    history:      2023-02-14 06:59:06 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...


In [6]:
print(lat)

<xarray.DataArray 'latitude' (latitude: 17)>
array([22.  , 21.75, 21.5 , 21.25, 21.  , 20.75, 20.5 , 20.25, 20.  , 19.75,
       19.5 , 19.25, 19.  , 18.75, 18.5 , 18.25, 18.  ], dtype=float32)
Coordinates:
  * latitude  (latitude) float32 22.0 21.75 21.5 21.25 ... 18.75 18.5 18.25 18.0
Attributes:
    units:      degrees_north
    long_name:  latitude


In [12]:
print(ds['time'])

<xarray.DataArray 'time' (time: 120)>
array(['2013-01-01T00:00:00.000000000', '2013-02-01T00:00:00.000000000',
       '2013-03-01T00:00:00.000000000', '2013-04-01T00:00:00.000000000',
       '2013-05-01T00:00:00.000000000', '2013-06-01T00:00:00.000000000',
       '2013-07-01T00:00:00.000000000', '2013-08-01T00:00:00.000000000',
       '2013-09-01T00:00:00.000000000', '2013-10-01T00:00:00.000000000',
       '2013-11-01T00:00:00.000000000', '2013-12-01T00:00:00.000000000',
       '2014-01-01T00:00:00.000000000', '2014-02-01T00:00:00.000000000',
       '2014-03-01T00:00:00.000000000', '2014-04-01T00:00:00.000000000',
       '2014-05-01T00:00:00.000000000', '2014-06-01T00:00:00.000000000',
       '2014-07-01T00:00:00.000000000', '2014-08-01T00:00:00.000000000',
       '2014-09-01T00:00:00.000000000', '2014-10-01T00:00:00.000000000',
       '2014-11-01T00:00:00.000000000', '2014-12-01T00:00:00.000000000',
       '2015-01-01T00:00:00.000000000', '2015-02-01T00:00:00.000000000',
       '2015-

In [10]:
sst.sel(longitude=110.25, latitude=20.0)

<xarray.DataArray 'sst' (time: 120, expver: 2)>
array([[292.5726 ,       nan],
       [293.3576 ,       nan],
       [294.83698,       nan],
       ...,
       [      nan, 300.44785],
       [      nan, 298.16986],
       [      nan, 295.0635 ]], dtype=float32)
Coordinates:
    longitude  float32 110.2
    latitude   float32 20.0
  * expver     (expver) int32 1 5
  * time       (time) datetime64[ns] 2013-01-01 2013-02-01 ... 2022-12-01
Attributes:
    units:      K
    long_name:  Sea surface temperature

In [9]:
print(sst)

<xarray.DataArray 'sst' (time: 120, expver: 2, latitude: 17, longitude: 17)>
array([[[[      nan, ...,       nan],
         ...,
         [297.80298, ..., 297.31964]],

        [[      nan, ...,       nan],
         ...,
         [      nan, ...,       nan]]],


       ...,


       [[[      nan, ...,       nan],
         ...,
         [      nan, ...,       nan]],

        [[      nan, ...,       nan],
         ...,
         [299.1544 , ..., 298.91025]]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 108.0 108.2 108.5 108.8 ... 111.5 111.8 112.0
  * latitude   (latitude) float32 22.0 21.75 21.5 21.25 ... 18.5 18.25 18.0
  * expver     (expver) int32 1 5
  * time       (time) datetime64[ns] 2013-01-01 2013-02-01 ... 2022-12-01
Attributes:
    units:      K
    long_name:  Sea surface temperature
