In [1]:
import xarray as xr
import numpy as np
import os
import arrow
import pandas as pd
import metpy.calc as mpcalc
from metpy.units import units

In [2]:
fcHour_list = np.array(list(range(0, 72+1, 3)) + list(range(78, 240+1, 6)))
fcHour_list_target = np.array(range(0, 240+1, 1))

In [4]:
dir_path = 'H:/github/python/seafog/data/CFdata/concat/'
file_name = '201810-202205_lon110.25_lat20.125.sstk.nc'
ds = xr.open_dataset(f'{dir_path}{file_name}')

In [8]:
iHour_target = 5
if(iHour_target in fcHour_list): 
    print('已存在时间')
else:
    # 寻找最近的两个值
    hour_distance = fcHour_list - iHour_target
    left_shift  = np.max(hour_distance[hour_distance<0])
    right_shift = np.min(hour_distance[hour_distance>0])
    varname = f'{"sstk"}{iHour_target:0>3d}'
    left_hour = iHour_target + left_shift
    right_hour = iHour_target + right_shift 
    varname_left = f'{"sstk"}{left_hour:0>3d}'
    varname_right = f'{"sstk"}{right_hour:0>3d}'
    with xr.set_options(keep_attrs=True):
        ds[varname] = (ds[varname_left]*(right_hour-iHour_target) + ds[varname_right]*(iHour_target-left_hour))/(right_hour-left_hour)

sstk003 sstk005 sstk006


In [14]:
with xr.set_options(keep_attrs=True):
    ds['sstk005'] = (ds['sstk003']*(right_hour-iHour_target) + ds['sstk006']*(iHour_target-left_hour))/(right_hour-left_hour)
print(ds['sstk005'])

<xarray.DataArray 'sstk005' (time: 2678)>
array([301.90176, 301.7373 , 301.69614, ..., 301.0436 , 301.5189 ,
       301.1753 ], dtype=float32)
Coordinates:
    lon      float32 110.2
    lat      float32 20.12
  * time     (time) datetime64[ns] 2018-10-01 ... 2022-05-31T12:00:00
Attributes:
    name:           sstk
    valid_min:      0.0
    standard_name:  sea_surface_skin_temperature
    units:          K
    long_name:      sea surface temperature
    short_name:     SST


<xarray.DataArray 'sstk005' (time: 2678)>
array([301.90176, 301.7373 , 301.69614, ..., 301.0436 , 301.5189 ,
       301.1753 ], dtype=float32)
Coordinates:
    lon      float32 110.2
    lat      float32 20.12
  * time     (time) datetime64[ns] 2018-10-01 ... 2022-05-31T12:00:00
Attributes:
    name:           sstk
    valid_min:      0.0
    standard_name:  sea_surface_skin_temperature
    units:          K
    long_name:      sea surface temperature
    short_name:     SST


In [11]:
ds['sstk003']

<xarray.DataArray 'sstk003' (time: 2678)>
array([301.85278, 301.77393, 301.64014, ..., 301.0542 , 301.39697, 301.188  ],
      dtype=float32)
Coordinates:
    lon      float32 ...
    lat      float32 ...
  * time     (time) datetime64[ns] 2018-10-01 ... 2022-05-31T12:00:00
Attributes:
    name:           sstk
    valid_min:      0.0
    standard_name:  sea_surface_skin_temperature
    units:          K
    long_name:      sea surface temperature
    short_name:     SST