In [7]:
import xarray as xr
import numpy as np

In [2]:
file0 = '201810-202101_lon110.25_lat20.125.sstk.nc'
file1 = '202102-202103_lon110.25_lat20.125.sstk.nc'
dirPath = 'H:/github/python/seafog/data/'

In [12]:
config = {
    'sstk':{
        'name':'sstk',
        'missing_value': -999.9,
        '_FillValue':  -999.9,
        'valid_min': 0.0,
        'standard_name': 'sea_surface_skin_temperature',
        'units': 'K',
        'long_name': 'sea surface temperature',
        'short_name': 'SST',
    },
    'visi':{
        'name':'visi',
        'missing_value': -999.9,
        '_FillValue':  -999.9,
        'valid_min': 0.0,
        'standard_name': 'visibility_in_air',
        'units': 'm',
        'long_name': 'visibility',
        'short_name': 'visibility',
    },
    't2md':{
        'name':'t2md',
        'missing_value': -999.9,
        '_FillValue':  -999.9,
        'valid_min': 0.0,
        'standard_name': 'dew_point_temperature',
        'units': 'K',
        'long_name': 'dew point',
        'short_name': 'Td',
    },
    't2mm':{
        'name':'t2mm',
        'missing_value': -999.9,
        '_FillValue':  -999.9,
        'valid_min': 0.0,
        'standard_name': 'air_temperature',
        'units': 'K',
        'long_name': 'air temperature in 2 metre',
        'short_name': 'T2m',
    },
    'rhum':{
        'name':'rhum',
        'missing_value': -999.9,
        '_FillValue':  -999.9,
        'valid_min': 0.0,
        'standard_name': 'relative_humidity',
        'units': '1',
        'long_name': 'relative_humidity',
        'short_name': 'RH',
    },
    'temp':{
        'name':'rhum',
        'missing_value': -999.9,
        '_FillValue':  -999.9,
        'valid_min': 0.0,
        'standard_name': 'air_temperature',
        'units': 'K',
        'long_name': 'air temperature',
        'short_name': 'Temp',
    },
}

In [3]:
ds01 = xr.open_dataset(dirPath + file0)
ds02 = xr.open_dataset(dirPath + file1)

In [6]:
print(ds01['sstk012'])

<xarray.DataArray 'sstk012' (time: 1708, level: 1)>
array([[301.885  ],
       [301.62476],
       [301.687  ],
       ...,
       [291.82056],
       [292.15308],
       [291.86548]], dtype=float32)
Coordinates:
    lon      float32 ...
    lat      float32 ...
  * level    (level) float32 0.0
  * time     (time) datetime64[ns] 2018-10-01 ... 2021-01-31T12:00:00


In [9]:
sstk = ds01['sstk012']
sstk = xr.where(sstk<0, np.nan, sstk)
sstk.fillna(-999.9)
print(sstk)

<xarray.DataArray 'sstk012' (time: 1708, level: 1)>
array([[301.885  ],
       [301.62476],
       [301.687  ],
       ...,
       [291.82056],
       [292.15308],
       [291.86548]], dtype=float32)
Coordinates:
    lon      float32 110.2
    lat      float32 20.12
  * level    (level) float32 0.0
  * time     (time) datetime64[ns] 2018-10-01 ... 2021-01-31T12:00:00


In [13]:
sstk.attrs = config['sstk']

In [15]:
sstk.drop_dims("level")

AttributeError: 'DataArray' object has no attribute 'drop_dims'

In [17]:
ds01['sstk012'] = sstk
print(ds01['sstk012'])

<xarray.DataArray 'sstk012' (time: 1708, level: 1)>
array([[301.885  ],
       [301.62476],
       [301.687  ],
       ...,
       [291.82056],
       [292.15308],
       [291.86548]], dtype=float32)
Coordinates:
    lon      float32 110.2
    lat      float32 20.12
  * level    (level) float32 0.0
  * time     (time) datetime64[ns] 2018-10-01 ... 2021-01-31T12:00:00
Attributes:
    name:           sstk
    missing_value:  -999.9
    _FillValue:     -999.9
    valid_min:      0.0
    standard_name:  sea_surface_skin_temperature
    units:          K
    long_name:      sea surface temperature
    short_name:     SST


In [18]:
ds01['sstk012']

<xarray.DataArray 'sstk012' (time: 1708, level: 1)>
array([[301.885  ],
       [301.62476],
       [301.687  ],
       ...,
       [291.82056],
       [292.15308],
       [291.86548]], dtype=float32)
Coordinates:
    lon      float32 110.2
    lat      float32 20.12
  * level    (level) float32 0.0
  * time     (time) datetime64[ns] 2018-10-01 ... 2021-01-31T12:00:00
Attributes:
    name:           sstk
    missing_value:  -999.9
    _FillValue:     -999.9
    valid_min:      0.0
    standard_name:  sea_surface_skin_temperature
    units:          K
    long_name:      sea surface temperature
    short_name:     SST

In [19]:
ds01.drop_dims("level")

<xarray.Dataset>
Dimensions:  (time: 1708)
Coordinates:
    lon      float32 110.2
    lat      float32 20.12
  * time     (time) datetime64[ns] 2018-10-01 ... 2021-01-31T12:00:00
Data variables:
    flag     (time) float32 1.0 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0 1.0 1.0
    stat     (time) float32 1.0 0.0 0.0 0.0 0.0 0.0 ... 1.0 1.0 1.0 1.0 1.0 1.0
    tstr     (time) float32 1.001e+05 1.001e+05 1.002e+05 ... 1.31e+04 1.311e+04
    ystr     (time) float32 2.018e+03 2.018e+03 ... 2.021e+03 2.021e+03
Attributes:
    DODS_EXTRA.Unlimited_Dimension:  time

In [20]:
ds01['sstk012']

<xarray.DataArray 'sstk012' (time: 1708, level: 1)>
array([[301.885  ],
       [301.62476],
       [301.687  ],
       ...,
       [291.82056],
       [292.15308],
       [291.86548]], dtype=float32)
Coordinates:
    lon      float32 110.2
    lat      float32 20.12
  * level    (level) float32 0.0
  * time     (time) datetime64[ns] 2018-10-01 ... 2021-01-31T12:00:00
Attributes:
    name:           sstk
    missing_value:  -999.9
    _FillValue:     -999.9
    valid_min:      0.0
    standard_name:  sea_surface_skin_temperature
    units:          K
    long_name:      sea surface temperature
    short_name:     SST

In [21]:
sstk[:,0]

<xarray.DataArray 'sstk012' (time: 1708)>
array([301.885  , 301.62476, 301.687  , ..., 291.82056, 292.15308,
       291.86548], dtype=float32)
Coordinates:
    lon      float32 110.2
    lat      float32 20.12
    level    float32 0.0
  * time     (time) datetime64[ns] 2018-10-01 ... 2021-01-31T12:00:00
Attributes:
    name:           sstk
    missing_value:  -999.9
    _FillValue:     -999.9
    valid_min:      0.0
    standard_name:  sea_surface_skin_temperature
    units:          K
    long_name:      sea surface temperature
    short_name:     SST

In [34]:
varNamePrefix = 'sstk'
timeList = list(range(0, 72+1, 3)) + list(range(78, 240+1, 6))
varNameList = list(map(lambda time: '{}{:0>3d}'.format(varNamePrefix, time), timeList))
print(varNameList)

['sstk000', 'sstk003', 'sstk006', 'sstk009', 'sstk012', 'sstk015', 'sstk018', 'sstk021', 'sstk024', 'sstk027', 'sstk030', 'sstk033', 'sstk036', 'sstk039', 'sstk042', 'sstk045', 'sstk048', 'sstk051', 'sstk054', 'sstk057', 'sstk060', 'sstk063', 'sstk066', 'sstk069', 'sstk072', 'sstk078', 'sstk084', 'sstk090', 'sstk096', 'sstk102', 'sstk108', 'sstk114', 'sstk120', 'sstk126', 'sstk132', 'sstk138', 'sstk144', 'sstk150', 'sstk156', 'sstk162', 'sstk168', 'sstk174', 'sstk180', 'sstk186', 'sstk192', 'sstk198', 'sstk204', 'sstk210', 'sstk216', 'sstk222', 'sstk228', 'sstk234', 'sstk240']


In [29]:
for letter in 'Python':     # 第一个实例
   print('当前字母 :', letter)

当前字母 : P
当前字母 : y
当前字母 : t
当前字母 : h
当前字母 : o
当前字母 : n
